services:
  web-api:
    image: t2junior:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5053:5053"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
